load("@rules_rust//rust:defs.bzl", "rust_binary")

package(default_visibility = ["//visibility:public"])

rust_binary(
    name = "problem_1",
    srcs = ["src/problem_1.rs"],
    data = ["src/problem_1.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_2",
    srcs = ["src/problem_2.rs"],
    data = ["src/problem_2.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_3",
    srcs = ["src/problem_3.rs"],
    data = ["src/problem_3.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_5",
    srcs = ["src/problem_5.rs"],
    data = ["src/problem_5.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_6",
    srcs = ["src/problem_6.rs"],
    data = ["src/problem_6.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_7",
    srcs = ["src/problem_7.rs"],
    data = ["src/problem_7.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_8",
    srcs = ["src/problem_8.rs"],
    data = ["src/problem_8.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_8_v2",
    srcs = ["src/problem_8_v2.rs"],
    data = ["src/problem_8.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_9",
    srcs = ["src/problem_9.rs"],
    data = ["src/problem_9.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_10",
    srcs = ["src/problem_10.rs"],
    data = ["src/problem_10.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_11",
    srcs = ["src/problem_11.rs"],
    data = ["src/problem_11.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_12",
    srcs = ["src/problem_12.rs"],
    data = ["src/problem_12.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_13",
    srcs = ["src/problem_13.rs"],
    data = ["src/problem_13.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_14",
    srcs = ["src/problem_14.rs"],
    data = ["src/problem_14.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_15",
    srcs = ["src/problem_15.rs"],
    data = ["src/problem_15.input"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

# rust_binary(
#     name = "problem_16",
#     srcs = ["src/problem_16.rs"],
#     data = ["src/problem_16.input"],
#     deps = [
#       "//source/rust/cargo:itertools",
#     ],
# )

rust_binary(
    name = "problem_17",
    srcs = ["src/problem_17.rs"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)

rust_binary(
    name = "problem_21",
    srcs = ["src/problem_21.rs"],
    deps = [
      "//source/rust/cargo:itertools",
    ],
)
