load("@io_bazel_rules_docker//container:container.bzl", "container_image",)
package(default_visibility = ["//infra:__subpackages__"])

container_image(
    name = "image",
    base = "//infra/images/base",
)
