name: Java CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build and Test
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: test
      - name: Create Fat Jar
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: fatJar
      - name: Get AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::270025496640:role/LambdaFunctionCodeUpdater
          aws-region: us-west-2
          role-session-name: lambda-uploader
      - name: Upload Fat Jar to lambda
        run: |
          aws lambda update-function-code --function-name colorpicker --zip-file fileb://`pwd`/build/libs/mealmate-fat.jar
